[workspace]
members = [
    "avesia",
    "gpu/avesia-render",
    "backend/avesia-desktop",
    "backend/avesia-webserver",
    "avesia-mmd",
]
default-members = [
    "avesia",
    "gpu/avesia-render",
]
resolver = "2"
