[workspace]
members = [
    "avesia",
    "avesia-desktop",
    "avesia-render",
    "avesia-server",
    "avesia-mmd"
]

default-members = [
    "avesia",
    "avesia-desktop",
    "avesia-render",
    "avesia-server",
]
