version: '3'

vars:
  # release | debug
  PROFILE: release

includes: 
  web:
    taskfile: ./ui/avesia-web/Taskfile.yml

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - task: build-renderer-wasm
      - task: build-web
      - task: build-app

  dev:
    deps: [build-web-dev, build-renderer-wasm, run-app-dev]

  build-web:
    cmds:
      - task: web:build-web
  
  build-renderer-wasm:
    cmds:
      - task: build-renderer-{{.PROFILE}}

  build-renderer-release:
    cmds:
      - cargo build -p avesia-render --target=wasm32-unknown-unknown --release
      - wasm-pack build ./gpu/avesia-render --release --out-dir ../../ui/avesia-render-wasm
  
  build-renderer-debug:
    cmds:
      - cargo build -p avesia-render --target=wasm32-unknown-unknown
      - wasm-pack build ./gpu/avesia-render --dev --out-dir ../../ui/avesia-render-wasm

  build-app:
    cmds:
      - task: build-app-{{.PROFILE}}

  build-app-release:
    cmds:
      - cargo build --bin avesia --release
  
  build-app-debug:
    cmds:
      - cargo build --bin avesia

  build-web-dev:
    cmds:
      - task: web:build-web-dev

  run-app-dev:
    cmds:
      - cargo run --bin avesia -- desktop http://localhost:8513
