# these tasks should be run in the root directory.

version: '3'

tasks:
  build-web:
    dir: ui/avesia-web
    cmds:
      - npm install
      - npm run build

  build-web-dev:
    dir: ui/avesia-web
    cmds:
      - npm install
      - npm run dev
